services:
  mongodb:
    image: mongo:7.0
    container_name: etl-specification-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - etl-network
  etl-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: etl-specification-api
    restart: unless-stopped
    ports:
      - '7001:80'
      - '7002:443'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - MongoDB__ConnectionString=mongodb://admin:password123@mongodb:27017
      - MongoDB__DatabaseName=ETLSpecifications
      - MongoDB__CollectionName=Specifications
    depends_on:
      - mongodb
    networks:
      - etl-network

volumes:
  mongodb_data:

networks:
  etl-network:
    driver: bridge
